version: '3.4'

networks:
    teatro:

volumes:
    sqlserver-data:
        driver: local
        
services:
    db:
        container_name: dbContainer
        image: mcr.microsoft.com/mssql/server:2019-CU21-ubuntu-20.04
        ports:
            - 8002:1433
        networks:
            - teatro
        volumes:
            - sqlserver-data:/var/opt/mssql    
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=<YourStrong@Passw0rd>
    api:
        container_name: apiContainer
        image: apidb-pizza:1.0
        ports:
            - 8001:80
        networks:
            - teatro    
        build:
            context: .
            dockerfile: API/Dockerfile
        depends_on:
            - db
