// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teatro.Data;

#nullable disable

namespace Teatro.Data.Migrations
{
    [DbContext(typeof(TeatroContext))]
    [Migration("20240225160816_GeneracionDeAsientos")]
    partial class GeneracionDeAsientos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Teatro.Models.Asiento", b =>
                {
                    b.Property<int>("AsientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsientoId"), 1L, 1);

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroAsiento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AsientoId");

                    b.ToTable("Asientos");

                    b.HasData(
                        new
                        {
                            AsientoId = 1,
                            NumeroAsiento = "A1"
                        },
                        new
                        {
                            AsientoId = 2,
                            NumeroAsiento = "A2"
                        },
                        new
                        {
                            AsientoId = 3,
                            NumeroAsiento = "A3"
                        },
                        new
                        {
                            AsientoId = 4,
                            NumeroAsiento = "A4"
                        },
                        new
                        {
                            AsientoId = 5,
                            NumeroAsiento = "A5"
                        },
                        new
                        {
                            AsientoId = 6,
                            NumeroAsiento = "A6"
                        },
                        new
                        {
                            AsientoId = 7,
                            NumeroAsiento = "B1"
                        },
                        new
                        {
                            AsientoId = 8,
                            NumeroAsiento = "B2"
                        },
                        new
                        {
                            AsientoId = 9,
                            NumeroAsiento = "B3"
                        },
                        new
                        {
                            AsientoId = 10,
                            NumeroAsiento = "B4"
                        },
                        new
                        {
                            AsientoId = 11,
                            NumeroAsiento = "B5"
                        },
                        new
                        {
                            AsientoId = 12,
                            NumeroAsiento = "B6"
                        },
                        new
                        {
                            AsientoId = 13,
                            NumeroAsiento = "B7"
                        },
                        new
                        {
                            AsientoId = 14,
                            NumeroAsiento = "B8"
                        },
                        new
                        {
                            AsientoId = 15,
                            NumeroAsiento = "B9"
                        },
                        new
                        {
                            AsientoId = 16,
                            NumeroAsiento = "B10"
                        },
                        new
                        {
                            AsientoId = 17,
                            NumeroAsiento = "B11"
                        },
                        new
                        {
                            AsientoId = 18,
                            NumeroAsiento = "B12"
                        },
                        new
                        {
                            AsientoId = 19,
                            NumeroAsiento = "C1"
                        },
                        new
                        {
                            AsientoId = 20,
                            NumeroAsiento = "C2"
                        },
                        new
                        {
                            AsientoId = 21,
                            NumeroAsiento = "C3"
                        },
                        new
                        {
                            AsientoId = 22,
                            NumeroAsiento = "C4"
                        },
                        new
                        {
                            AsientoId = 23,
                            NumeroAsiento = "C5"
                        },
                        new
                        {
                            AsientoId = 24,
                            NumeroAsiento = "C6"
                        });
                });

            modelBuilder.Entity("Teatro.Models.Obra", b =>
                {
                    b.Property<int>("ObraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObraId"), 1L, 1);

                    b.Property<string>("Descripción")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioEntrada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Título")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObraId");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("Teatro.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"), 1L, 1);

                    b.Property<int>("AsientoId")
                        .HasColumnType("int");

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ReservaId");

                    b.HasIndex("AsientoId");

                    b.HasIndex("ObraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Teatro.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"), 1L, 1);

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Rol")
                        .HasColumnType("bit");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            Contraseña = "admin",
                            CorreoElectronico = "admin@admin.com",
                            Nombre = "admin",
                            Rol = true
                        });
                });

            modelBuilder.Entity("Teatro.Models.Reserva", b =>
                {
                    b.HasOne("Teatro.Models.Asiento", "Asiento")
                        .WithMany()
                        .HasForeignKey("AsientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teatro.Models.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teatro.Models.Usuario", null)
                        .WithMany("ListReservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asiento");

                    b.Navigation("Obra");
                });

            modelBuilder.Entity("Teatro.Models.Usuario", b =>
                {
                    b.Navigation("ListReservas");
                });
#pragma warning restore 612, 618
        }
    }
}
