// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Teatro.Data;

#nullable disable

namespace Teatro.Data.Migrations
{
    [DbContext(typeof(TeatroContext))]
    partial class TeatroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Teatro.Models.Asiento", b =>
                {
                    b.Property<int>("AsientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsientoId"), 1L, 1);

                    b.Property<int?>("DetalleSalaId")
                        .HasColumnType("int");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("NumeroAsiento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroFila")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AsientoId");

                    b.HasIndex("DetalleSalaId");

                    b.ToTable("Asientos");
                });

            modelBuilder.Entity("Teatro.Models.DetalleSala", b =>
                {
                    b.Property<int>("DetalleSalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleSalaId"), 1L, 1);

                    b.Property<int>("ObraId")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("DetalleSalaId");

                    b.HasIndex("ObraId");

                    b.HasIndex("SalaId");

                    b.ToTable("DetalleSalas");
                });

            modelBuilder.Entity("Teatro.Models.Obra", b =>
                {
                    b.Property<int>("ObraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObraId"), 1L, 1);

                    b.Property<string>("Descripción")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioEntrada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Título")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObraId");

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("Teatro.Models.Reserva", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaId"), 1L, 1);

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ReservaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Teatro.Models.ReservaSala", b =>
                {
                    b.Property<int>("ReservaSalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservaSalaId"), 1L, 1);

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("ReservaSalaId");

                    b.HasIndex("ReservaId");

                    b.HasIndex("SalaId");

                    b.ToTable("ReservaSalas");
                });

            modelBuilder.Entity("Teatro.Models.Sala", b =>
                {
                    b.Property<int>("SalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaId"), 1L, 1);

                    b.Property<string>("NombreSala")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SalaId");

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("Teatro.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"), 1L, 1);

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Teatro.Models.Asiento", b =>
                {
                    b.HasOne("Teatro.Models.DetalleSala", null)
                        .WithMany("Asientos")
                        .HasForeignKey("DetalleSalaId");
                });

            modelBuilder.Entity("Teatro.Models.DetalleSala", b =>
                {
                    b.HasOne("Teatro.Models.Obra", "Obra")
                        .WithMany()
                        .HasForeignKey("ObraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teatro.Models.Sala", "Sala")
                        .WithMany("Detalles")
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obra");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Teatro.Models.Reserva", b =>
                {
                    b.HasOne("Teatro.Models.Usuario", "Usuario")
                        .WithMany("ListReservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Teatro.Models.ReservaSala", b =>
                {
                    b.HasOne("Teatro.Models.Reserva", "Reserva")
                        .WithMany("ListSalas")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Teatro.Models.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Teatro.Models.DetalleSala", b =>
                {
                    b.Navigation("Asientos");
                });

            modelBuilder.Entity("Teatro.Models.Reserva", b =>
                {
                    b.Navigation("ListSalas");
                });

            modelBuilder.Entity("Teatro.Models.Sala", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Teatro.Models.Usuario", b =>
                {
                    b.Navigation("ListReservas");
                });
#pragma warning restore 612, 618
        }
    }
}
